 # Generated by Django 4.1.4 on 2022-12-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descript ion', models.TextField()),
                ('technology', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='img/')),
            ],
        ),
    ]
